### ISSUE TITLE
Assertion failed: (sizeof(osc::int32) == 4)

### ISSUE THREAD

**Issue by cannc4** [isyuck/tidalrytm#1]
Hey, this is pretty dope, and wanted to give it a go and use it with my Nord Modular. 
SC has always been problematic on my end with the extra overhead so this is pretty useful if one wants to just see tidal and send out messages

I am on M1 Monterey and got rtmidi + oscpack installed via homebrew. 

When I run `./tidalyrtm` I am seeing it boot up and listen for the messages but then once Tidal is booted I get this
```
Assertion failed: (sizeof(osc::int32) == 4), function ValidateSize, file OscReceivedElements.h, line 123.
[1]    50198 abort      ./tidalrytm
```

Thought I'd share here but I'll be looking into the problem as this is a nice way to use tidal :)

**Comment by isyuck** [comment]
hello & thanks! i actually had the same issue, i'm primarily using this on M1 Monterey also. i fixed it by removing the oscpack installed through brew (`brew uninstall oscpack`), then cloning oscpack from [here](https://github.com/RossBencina/oscpack), changing the assertions on lines 123 & 124 in `osc/OscReceivedElements.h` from

```cpp
assert(sizeof(osc::int32) == 4);
assert(sizeof(osc::uint32) == 4);
```

to

```cpp
assert(sizeof(osc::int32) == 8);
assert(sizeof(osc::uint32) == 8);
```

and building oscpack via the instructions in their repo. 

if you rebuild tidalrytm it should find the new oscpack and work correctly.

p.s., i'm interested to see what you do with your nord modular! the cpp program is actually pretty device agnostic, all of the configuration to make it rytm specific is done in `BootTidal.hs`. perhaps `tidalrytm` isn't the best name...

**Comment by cannc4** [comment]
thanks for the tip @isyuck that worked just fine and I was able to get it running. Got a few other suggestions but I'll take em to another issue. ta!
